tech_layoffs_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: admin
      password: admin123
      port: 5432
      dbname: tech_layoffs_dw
      schema: public
      threads: 4
